name: GitHub Profile 3D Contrib

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          # GitHub username
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A profile-3d-contrib
            git commit -m "Update 3D contribution graph" || exit 0
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
